<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<div id="privacy_content" class="bg_color common_radius common_mar_pad">
<h1> Privacy Policy for Podcastpedia</h1>
<p><b>Podcastpedia.org respects your privacy.</b></p>
<p>Any personal information you provide to us including and similar to your name and e-mail address will not be released, sold, or rented to any entities or individuals outside of Pocastpedia.org.</p>

<p><b>External Sites.</b></p>
<p>Podcastpedia.org is not responsible for the content of external internet sites. You are advised to read the privacy policy of external sites before disclosing any personal information.</p>

<p> If you require any more information or have any questions about our privacy policy, please feel free to contact us by email at <b>contact [AT] podcastpedia DOT org</b></p>
<p>At www.podcastpedia.org we consider the privacy of our visitors to be extremely important. This privacy policy document describes in detail the types of personal information is collected and recorded by www.podcastpedia.org and how we use it. </p><p> <b>Log Files</b><br> Like many other Web sites, www.podcastpedia.org makes use of log files. These files merely logs visitors to the site - usually a standard procedure for hosting companies and a part of hosting services's analytics. The information inside the log files includes internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date/time stamp, referring/exit pages, and possibly the number of clicks. This information is used to analyze trends, administer the site, track user's movement around the site, and gather demographic information. IP addresses, and other such information are not linked to any information that is personally identifiable. </p>

<p><b>Cookies </b></p>
<p>A "cookie" is a small data text file that is placed in your browser and allows Codingpedia.org to recognize you each time you visit this site(customisation etc). Cookies themselves do not contain any personal information, and Codingpedia.org does not use cookies to collect personal information. They are only used to improve your experience while visiting our website. Cookies may also be used by 3rd party content providers such as newsfeeds.</p>

<p> If you wish to disable cookies, you may do so through your individual browser options. More detailed information about cookie management with specific web browsers can be found at the browsers' respective websites. <a href="http://www.privacypolicyonline.com/what-are-cookies">What Are Cookies?</a></p>

<p><strong>Children's Information</strong><br />We believe it is important to provide added protection for children online. We encourage parents and guardians to spend time online with their children to observe, participate in and/or monitor and guide their online activity.
www.podcastpedia.org does not knowingly collect any personally identifiable information from children under the age of 13.  If a parent or guardian believes that www.podcastpedia.org has in its database the personally-identifiable information of a child under the age of 13, please contact us immediately (using the contact in the first paragraph) and we will use our best efforts to promptly remove such information from our records.

<p>
<b>Online Privacy Policy Only</b><br />
This privacy policy applies only to our online activities and is valid for visitors to our website and regarding information shared and/or collected there.
This policy does not apply to any information collected offline or via channels other than this website.</p>
<p><b>Consent</b><br />
By using our website, you hereby consent to our privacy policy and agree to its terms.
</p><br /><br /><p><b>Update</b><br />This Privacy Policy was last updated on: Monday, July 8th, 2013.
<a href="http://www.PrivacyPolicyOnline.com" title="PrivacyPolicyOnline.com Approved Site" target="_blank"><img src="http://www.privacypolicyonline.com/images/privacypolicyonline-seal.png" border="0" alt="Privacy Policy Online Approved Site" align="right" /></a><br /><em>Should we update, amend or make any changes to our privacy policy, those changes will be posted here.</em>
<br /><br /></p>
<!-- END of Privacy Policy || Generated by http://www.PrivacyPolicyOnline.com || -->
</div>
